# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Global Dependencies
	parchment_mc_version=1.21.8
	parchment_version=2025.09.14
	coroutil_version=1.3.8
	libbulletjme_version = 17.4.0

# Fabric Properties
    # check these on https://fabricmc.net/develop
	minecraft_version=1.21.8
    yarn_mappings=1.21.8+build.1
    loader_version=0.17.3

# Fabric Dependencies
	fabric_version=0.136.0+1.21.8

# Forge Properties
	forge_version=58.1.7
	minecraft_version_range=[1.21.8,1.22)
	forge_version_range=[58,)
	loader_version_range=[58,)

# Neoforge Properties
	neo_version=21.8.49
	neo_version_range=[21.8,)

# Mod Properties
	mod_id = weather2
	mod_name=Weather2
	mod_version = 1.21.0-2.8.5
	mod_description=Speeeeeeen
	maven_group = com.corosus.weather2
	archives_base_name = weather2
	mod_authors=Corosus
	mod_license=All Rights Reserved

ltextras_version=25.0.283
ltminigames_version=0.1.0-alpha+1222-gha
ltweather_version=1.21.8-1.0
tropicraft_version=9.9.1-beta+752-gha